events { }

http {
    # Server Context (Virtual Host)
    server {
        listen 80;
        server_name localhost;

        # Location Context (Reverse Proxy Example)
        location / {
            proxy_pass http://node:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Error Page handling
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}