name: Practice workflow

on: [push, pull_request]

concurrency:
    group: ${{ github.env }}-${{ github.workflow }}-${{ github.ref }}

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Setup node
              uses: actions/setup-node@v7
              with:
                node-version: 24.x
                cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Type checking
              run: npx tsc --noEmit

            - name: Run linting
              run: npm run lint

    test: 
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x, 24.x]

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Setup node
              uses: actions/setup-node@v7
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Run test 
              run: npm run test

            - name: Upload test result as artifact
              uses: actions/upload-artifact@v7
              with:
                path: 'test-result.txt'

    build: 
        needs:
          - lint
          - test

        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Setup node
              uses: actions/setup-node@v7
              with:
                node-version: 24.x

            - name: Install dependencies
              run: npm ci

            - name: Build the application
              run: npm run build

    build-and-push:
        needs: build

        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Setup node
              uses: actions/setup-node@v7

            - name: Configure AWS with credentials
              uses: aws-actions/configure-aws-credentials@v6
              with: 
                aws-region: ${{ secrets.AWS_REGION }}
                role-to-assume: ${{ secrets.AWS_ROLE }}
            
            - name: Login to AWS ECR 
              id: ecr-login
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag and push image
              env:
                ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
                ECR_REPOSITORY: my-app
                IMAGE_TAG: ${{ github.sha }} 
                ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}
              run: |
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$ENVIRONMENT-$IMAGE_TAG .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$ENVIRONMENT-$IMAGE_TAG
              # run: |
              #   docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
              #   docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    deploy:
        needs: build-and-push
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Copy docker-compose.yaml and nginx.conf to server
              uses: appleboy/scp-action@v1
              with: 
                host: ${{ secrets.SERVER_IP }}
                username: ${{ secrets.SERVER_USER }}
                key: ${{ secrets.SERVER_SSH_KEY }}
                source: "docker-compose.yaml, nginx.conf"
                target: "/home/ubuntu/app"
              
            - name: Deploy the application to server
              uses: appleboy/ssh-action@v1
              env:
                AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
                APPLICATION_PORT: ${{ secrets.APPLICATION_PORT }}
                IMAGE_TAG: ${{ github.sha }}
                ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}
              with: 
                host: ${{ secrets.SERVER_IP }}
                username: ${{ secrets.SERVER_USER }}
                key: ${{ secrets.SERVER_SSH_KEY }}
                envs: AWS_ACCOUNT_ID, AWS_REGION, APPLICATION_PORT, IMAGE_TAG, ENVIRONMENT
                script: |
                    # 1. Change to directory
                    cd /home/ubuntu/app

                    # 2. Export variables
                    export ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                    export ECR_REPOSITORY=my-app
                    export IMAGE_TAG=$ENVIRONMENT-$IMAGE_TAG
                    # export IMAGE_TAG=$IMAGE_TAG
                    export PORT=$APPLICATION_PORT

                    # 3. Login docker to registry
                    aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

                    # 4. Stop existing running container
                    docker stop api-server || true
                    docker rm api-server || true

                    # 5. Pull new image
                    docker compose pull 
                    docker compose up -d
 
                    # 6. Health check 
                    echo "Deploying application..."
                    for i in {1..10}; do
                        if [ "$(docker inspect --format '{{.State.Health.Status}}' api-server)" == "healthy" ]; then
                            echo "Deployment successfull..."
                            exit 0
                        fi
                        echo "Retrying! $((10-i)) retries left..."
                    done
                    echo "Deployment failed! Max retries exceeded..."
                    docker compose logs
                    exit 1