name: CI/CD workflow

on: 
    push:
        branches:
            - develop
        tags:
            - 'v*'
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest

        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7

            - name: Setup node environment
              uses: actions/setup-node@v7
              with: 
                node-version: 24.x
                cache: npm 

            - name: Install dependencies
              run: npm run ci

            - name: Perform type checking
              run: npx tsc --noEmit

            - name: Perform linting
              run: npm run lint

    test: 
        runs-on: ubuntu-latest

        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x, 24.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7

            - name: Setup node environment
              uses: actions/setup-node@v7
              with: 
                node-version: ${{ matrix.node-version }}
                cache: npm
        
            - name: Install dependencies
              run: npm run ci
              

            - name: Perform testing
              run: npm run test

            - name: Store the test result as artifact
              uses: actions/upload-artifact@v7
              with: 
                name: test-result
                path: 'test-result.txt'

    build: 
        needs:
          - lint
          - test

        runs-on: ubuntu-latest

        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7

            - name: Setup node environment
              uses: actions/setup-node@v7
              with: 
                node-version: 24.x
                cache: npm

            - name: Install dependencies
              run: npm run ci

            - name: Build the application
              run: npm run build

    build-and-push:
        needs: build

        runs-on: ubuntu-latest

        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                role-to-assume: ${{ secrets.AWS_ROLE }}
                region: ${{ secrets.AWS_REGION }}

            - name: Login to AWS ECR
              id: ecr-login
              uses: aws-actions/amazon-ecr-login@v2
            
            - name: Build, tag and push to ECR repository
              env:
                ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
                ECR_REPOSITORY: my-app
                IMAGE_TAG: ${{ github.sha }}
              run: |
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    deploy:
        needs: build-and-push

        runs-on: ubuntu-latest

        if: always() && (github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v'))

        environment: ${{ startsWith(github.ref, 'refs/tags/v') && 'prod' || 'staging' }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7

            - name: Copy docker-compose.yaml and nginx.conf to server
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.SERVER_IP }}
                username: ${{ secrets.SERVER_USER }}
                key: ${{ secrets.SERVER_SSH_KEY }}
                source: "docker-compose.yaml, nginx.conf"
                target: "/home/ubuntu/app"

            - name: Deploy application to server
              uses: appleboy/ssh-action@v1
              env:
                AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
                IMAGE_TAG: ${{ github.sha }}
                APPLICATION_PORT: ${{ secrets.APPLICATION_PORT }}
              with: 
                host: ${{ secrets.SERVER_IP }}
                username: ${{ secrets.SERVER_USER }}
                key: ${{ secrets.SERVER_SSH_KEY }}
                envs: AWS_ACCOUNT_ID, AWS_REGION, IMAGE_TAG, APPLICATION_PORT
                script: |
                    # 1. Move to /home/ubuntu/app
                    cd /home/ubuntu/app

                    # 2. Export variables
                    export ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                    export ECR_REPOSITORY=my-app
                    export IMAGE_TAG=$IMAGE_TAG

                    # 3. Create .env file
                    echo "PORT=$APPLICATION_PORT" > .env

                    # 4. Login docker to AWS ECR
                    aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

                    # 5. Stop existing running container
                    docker stop api-server || true
                    docker rm api-server || true

                    # 6. Run new container
                    docker compose pull
                    docker compose up -d

                    # 7. Perform healthcheck on application startup
                    echo "Deploying application..."
                    for i in {1..11}; do
                        if [ "$(docker inspect --format '{{.State.Health.Status}}' api-server)" == "healthy" ]; then
                            echo "Deployment successfull..."
                            exit 0
                        fi
                        echo "Retrying deployment! $((10-i)) retries left..."
                    done
                    echo "Deployment failed! Retries exceeded..."
                    docker compose logs
                    exit 1